# Generated by Django 4.0.4 on 2022-05-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_benefits',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_salary',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='skills_needed_1',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='skills_needed_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_needed_3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_needed_4',
            field=models.TextField(null=True),
        ),
    ]
