# Generated by Django 4.0.4 on 2022-05-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_api', '0002_job_job_benefits_job_job_salary_job_skills_needed_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_benefits',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='skills_needed_2',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='skills_needed_3',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='skills_needed_4',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
