# Generated by Django 4.0.4 on 2022-05-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_api', '0003_alter_job_job_benefits_alter_job_skills_needed_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_age', models.IntegerField()),
                ('employee_specialization', models.CharField(max_length=100)),
                ('employee_description', models.TextField()),
                ('employee_gpa', models.FloatField(max_length=3)),
                ('employee_degree', models.FileField(upload_to='')),
                ('skills_1', models.CharField(max_length=60)),
                ('skills_2', models.CharField(max_length=60)),
                ('skills_3', models.CharField(max_length=60)),
                ('skills_4', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=100)),
                ('employer_city', models.CharField(max_length=60)),
                ('employer_sub_city', models.CharField(max_length=60)),
                ('employer_function', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
        migrations.AlterField(
            model_name='job',
            name='skills_needed_1',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills_needed_2',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills_needed_3',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills_needed_4',
            field=models.CharField(max_length=60),
        ),
    ]
