# Generated by Django 4.0.4 on 2022-05-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_api', '0004_employeeprofile_employerprofile_delete_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='employee_degree',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='employee_degree_name',
            field=models.CharField(default=None, max_length=70),
            preserve_default=False,
        ),
    ]
