# Generated by Django 4.0.3 on 2022-06-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills_needed_2',
            field=models.CharField(default=None, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='skills_needed_3',
            field=models.CharField(default=None, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='skills_needed_4',
            field=models.CharField(default=None, max_length=60),
            preserve_default=False,
        ),
    ]
